### ISSUE TITLE
File naming error in Worksheet 3

### ISSUE THREAD

**Issue by DeeJay** [CamJam-EduKit/EduKit3#1]
re: Worksheet 3 -Running the Motors

On page 3 there are two references to invoking the code or editting it that mention a file "2-motors.py"

On page 2 the file that was created to hold this script was named "3-motors.py". (This name is also consistent with the content of this repository.)

(I don't think I can offer you a PR with a fix because the PDF is seen as a 'blob'.)

**Comment by GeekyTim** [comment]
Thanks - sorted a while ago
