### ISSUE TITLE
How are PDFs in this repo created?

### ISSUE THREAD

**Issue by Godley** [CamJam-EduKit/EduKit3#10]
Based on feedback from users within schools, these are fairly wordy for children to follow. I was planning to do some abridged versions of them which focus more on getting things moving/diagrams over large sections of text.
I'm just wondering where the PDFs here come from and thinking it would be good to move to using LaTeX for contribution purposes?

**Comment by GeekyTim** [comment]
The PDFs were generated from Word documents.  They are available upon request for special people ;-)
