### ISSUE TITLE
New at this - CamJam 3#

### ISSUE THREAD

**Issue by MannoManx** [CamJam-EduKit/EduKit3#13]
Sorry in advance if this is not the correct place to post --- 
I am having problems with the kit - 
my right motor is constantly on, what ever i do it just keeps going on...and on.... i have connected over many times, manually put in the code and then resulted in copy/paste x3 ...

Both right/left motor works with codes, once the right motors finishes with the code, it just continues to move forward, the left stops. 

Still as soon as i turn the motor battery pack to on, the right motors starts up/ The left side is fine (stops), and works with codes .. im going insane as this shouldn't be this hard! 

Any help would be great - Thanks J

**Comment by Pyroseza** [comment]
Hi@MannoManx, you might just have an issue with your wiring. Can you take a photo or describe your pins’ wiring?

Also which code are you copy pasting?

**Comment by GeekyTim** [comment]
Have you got this working yet?
