### ISSUE TITLE
GPIO Zero 6-distance.py not expected output

### ISSUE THREAD

**Issue by joostvdveen** [CamJam-EduKit/EduKit3#15]
I have an issue with EduKit3/CamJam Edukit 3 - GPIO Zero/Code/6-distance.py
if i run the code the screen output is Distance: 1.0 cm
when placing my hand before the sensor: Distance 0 cm

if i run the (old) GPIO code, the screen output is correct

**Comment by GeekyTim** [comment]
Which version of GPIOZero do you have?

**Comment by psion739** [comment]
Tim I will contact you Friday as I am on holiday at the moment. If this an order placed by Estuary League, I will be using Pi, latest version not Pi Zero.Off the top of my head I don't  have the details with me.John ThompsonOn 21 Aug 2018 16:10, Tim Richardson <notifications@github.com> wrote:Which version of GPIOZero do you have?

**Comment by GeekyTim** [comment]
No problem. But you do need to use the latest version of GPIOZero (1.4.1) as the previous version had the issue you describe.

**Comment by keithellis74** [comment]
Tim, I've got the same issue. The readings are in metres.  The ```* 100``` in line 18 is not being interpreted.  I found parentheses has to be inserted thus

    print("Distance: %.1f cm\n" % (sensor.distance * 100))

Also note I've added the new line character to the end of the print statement.  This makes it easier to read the readings.

Another note, in the pdf, on page 3, it tells you to save the file as ```5-distance.py```, this should be ```6-distance.py```

I'm using gpiozero 1.4.1

Good work though.  Thank you.
Keith.

**Comment by GeekyTim** [comment]
Thanks Keith!

*Thanks*

*Tim Richardson*
*Twitter: @Geeky_Tim*

**Comment by robmckinnon** [comment]
With the `master` branch code I also got the readings in metres.

After placing the parentheses as @keithellis74 suggested above, I got the readings in cm.

Maybe the parentheses fix should be made to repo code?

**Comment by evgprojects** [comment]
A PR to fix it https://github.com/CamJam-EduKit/EduKit3/pull/25
