### ISSUE TITLE
Worksheet 1 - Typo - EduKit3, not EduKit2

### ISSUE THREAD

**Issue by TotalSpaceshipguy** [CamJam-EduKit/EduKit3#19]
The last sentence on page 3 says...

"The code will be stored in the Code subfolder under the EduKit**2**/CamJam Edukit 3 – GPIO Zero
folder."

This should say "under the EduKit**3**/CamJam Edukit 3 – GPIO Zero folder."

**Comment by TotalSpaceshipguy** [comment]
Hi @GeekyTim 

The PDF download below still has the typo I reported, so I don't understand why this has been closed .

https://github.com/CamJam-EduKit/EduKit3/blob/master/CamJam%20Edukit%203%20-%20GPIO%20Zero/CamJam%20EduKit%203%20-%20Robotics%20Worksheet%201%20(GPIO%20Zero)%20-%20Introduction.pdf

Kind regards
Dom

**Comment by GeekyTim** [comment]
Sorry, I thought I had already addressed it - obviously not! Done now.

**Comment by TotalSpaceshipguy** [comment]
Thanks :-)
