### ISSUE TITLE
Adafruit attribution?

### ISSUE THREAD

**Issue by lurch** [CamJam-EduKit/EduKit3#2]
In https://github.com/RPi-Distro/python-gpiozero/issues/296#issuecomment-217824647 @GeekyTim mentions that the HC-SR04 image in Worksheet 6 comes from the Adafruit Fritzing library.

https://github.com/adafruit/Fritzing-Library/blob/master/README.md says

> Released under CC Attribution Share-Alike

I'm not a licensing expert, but does the "Attribution" aspect mean that Worksheet 6 ought to be giving credit to Adafruit for the HC-SR04 image?

And I dunno if the "ShareAlike" aspect of the Adafruit licence is compatible with the MIT licence of the CamJam worksheets? *shrug*

**Comment by GeekyTim** [comment]
TBH, I didn't look at that part. I downloaded the parts ages ago, and when
I created the diagrams used whatever was in Fritzing.  I will have to take
a look.

**Comment by lurch** [comment]
Also, on a slight side-note: given that the worksheets are licensed under the highly-permissive MIT licence, would it make sense for the 'source versions' of the PDFs to be uploaded too, to make it easier for people to make "remixed versions" if they wanted to?  (Of course this is entirely optional and completely up to you)

**Comment by GeekyTim** [comment]
People ca request the original versions if they wish. We have had various translations produced this way.
