### ISSUE TITLE
Why should the stop time minus start time greater than or equal to 0.04 seconds?

### ISSUE THREAD

**Issue by siddharthlaw** [CamJam-EduKit/EduKit3#29]
if StopTime - StartTime >= 0.04:
                print("Hold on there!  You're too close for me to see.")
                StopTime = StartTime
                break

Here is the code snippet in CamJam Worksheet.

**Comment by GeekyTim** [comment]
This is a 'fudge' because the sensor is not accurate at very close distances.

**Comment by siddharthlaw** [comment]
Hi Tim, Thank you for the confirmation. I am not sure why the value 0.04 was picked. Also, I am little bit confused on the distance would be larger if it greater than or equal to 0.04. Please confirm the details.
