### ISSUE TITLE
Why the value 0.04 seconds was picked for the time duration? 

### ISSUE THREAD

**Issue by siddharthlaw** [CamJam-EduKit/EduKit3#30]
Hi Tim, Thank you for the confirmation. I am not sure why the value 0.04 was picked. Also, I am little bit confused on the distance would be larger if it greater than or equal to 0.04. Please confirm the details.

**Comment by GeekyTim** [comment]
TBH I'm not sure. I suspect it is something to do with how quickly the sensor works.
