### ISSUE TITLE
motor controller board constantly turns one wheel when Pi is turned on

### ISSUE THREAD

**Issue by s9550110** [CamJam-EduKit/EduKit3#31]
Hi. Very new to Pi and CamJam. I've connected the board to a Pi Zero and Pi 400 with same result. Only way I can stop it is to run one of the scripts.

Thanks

James

**Comment by GeekyTim** [comment]
This is likely to be because the state of the GPIO pins will randomly be 0 or 1 until they are set by a program. This is usual.
