### ISSUE TITLE
Motors not working

### ISSUE THREAD

**Issue by eduardoctor** [CamJam-EduKit/EduKit3#32]
Hi, 

I Understand that this in an old project. However, I recently got the kit. and I have not been able to have the motors working. I re-wired everything checked with a multimeter that everything was getting power, checked the code but it does not work. Any ideas?

**Comment by GeekyTim** [comment]
Which raspberry pi are you using, and which version of Raspberry Pi OS?

Are you using a new set of batteries?

**Comment by eduardoctor** [comment]
Hello Tim, 

I appreciate your quick response. I am using the Raspberry pi 3B+ with Bullseye as OS. And I am using a brand new set of batteries.

**Comment by GeekyTim** [comment]
Thanks. I must admit I have not tried bullseye yet. It should work, but no
guarantee. I will hopefully try tomorrow.

One of the common problems is that the board has not been plugged onto the
Pi correctly. The diagrams on the worksheets should hopefully be explicit
enough, but if you have any concerns please let me know,and send a photo
if you can.

Tim

**Comment by eduardoctor** [comment]
I was also reluctant to try Bullseye because of the many bugs it has but I didn't see a problem given that the default is Python3. 
Do you suggest me to try it using Buster or a different version? I am attaching the photos of the wiring.  
![Edukit3_wiring](https://user-images.githubusercontent.com/71841555/147520403-c9954624-4d50-4602-9f7b-458c04b0c478.jpg)
![Edukit_GPIO-board](https://user-images.githubusercontent.com/71841555/147520411-9a028753-3338-47ca-8930-aec57e8a1e34.jpg)

**Comment by GeekyTim** [comment]
That is attached correctly.

I'll try bullseye later today.

**Comment by GeekyTim** [comment]
I have now tried the edukit 3 on Bullseye and can report that the code
works.

Do you see the red led on on the top of the board light up when you boot
the Pi?

*Thanks*

*Tim Richardson*
*Twitter: @Geeky_Tim*

**Comment by eduardoctor** [comment]
Hi Tim, 

Thank you for checking Bullseye. The red led lights up at boot and stays on while plugged to the pi. Also, the green led flashes intermittently at boot but it does not come up at all after that. I am worried that I might be dealing with a faulty board (?). I have tried different combinations using using Thonny as well as python 3 IDLE to run/edit the code (no errors):
Pi 3B with Bullseye (the first set up I tried) 
Pi 3B with Buster
Pi4 8Gb with Bullseye
Pi4 8Gb with Buster
Different SDcards.... No luck!

Thank you, 
-Eduardo

**Comment by GeekyTim** [comment]
If you purchased it recently then perhaps you could contact The PiHut?

**Comment by eduardoctor** [comment]
Will do. I appreciate your time. I hope you have an excellent new year. 

-Eduardo

**Comment by GeekyTim** [comment]
Did you get this sorted?
