### ISSUE TITLE
Using GPIOZero

### ISSUE THREAD

**Issue by tjguk** [CamJam-EduKit/EduKit3#6]
You absolutely must have been asked this question before, but I couldn't see anything in the Github issues: are you planning to update to use GPIOZero and/or would you be open to a PR to that effect?

Follow-on question, assuming that you are open to a PR: is the source of the PDFs available in some editable form?

**Comment by GeekyTim** [comment]
Yes, we will be updating to GPIO Zero 0 hopefully soon!
